[app]
debug = true
client_version = "0.1.0"

[cors]
allow_origins = ["http://127.0.0.1:5173", "http://localhost:5173"]

[database]
url = "postgresql+asyncpg://oneway:oneway@db:5432/oneway"
pool_size = 10
pool_timeout = 30
echo = false

[security]
secret_key = "dev-secret"
algorithm = "HS256"
access_token_expires_minutes = 60
refresh_token_expires_days = 7
jwt_issuer = "http://127.0.0.1:8000"
jwt_audience = "onewAy-api"

[paths]
client_dir = "[ROOT]/client"
module_dir = "[ROOT]/modules"
avatar_dir = "[ROOT]/server/backend/app/resources/avatars"

[other]
max_avatar_size_mb = 2

[testing]
testing = false

[testing.database]
url = ""
pool_size = 10
pool_timeout = 30
echo = false

[testing.security]
secret_key = ""
algorithm = "HS256"
access_token_expires_minutes = 15
refresh_token_expires_days = 7

[testing.paths]
client_dir = "[ROOT]/client"
module_dir = "[ROOT]/server/backend/tests/modules"
avatar_dir = "[ROOT]/server/backend/tests/resources/avatars"
