x-default-env: &default-env
  POSTGRES_DB: ${POSTGRES_DB:-oneway}
  POSTGRES_USER: ${POSTGRES_USER:-onewayuser}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_HOST: oneway-db

services:
  oneway-app:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    stdin_open: true
    tty: true
    environment:
      <<: *default-env
      REPO_URL: ${REPO_URL:-https://github.com/r3dwh33lbarrow/onewAy.git}
      REPO_REF: ${REPO_REF:-main}
      PROJECT_DIR: /workspace/oneway
      BACKEND_PORT: ${BACKEND_PORT:-8000}
      FRONTEND_PORT: ${FRONTEND_PORT:-5173}
      CLIENT_VERSION: ${CLIENT_VERSION:-0.1.0}
      SECURITY_SECRET_KEY: ${SECURITY_SECRET_KEY:-}
      PYTHONPATH: /workspace/oneway/server/backend
      SECRETS_DIR: /workspace/.secrets
    depends_on:
      oneway-db:
        condition: service_healthy
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - oneway-app-data:/workspace
      - oneway-secrets:/workspace/.secrets
      - ~/.ssh:/root/.ssh:ro

    restart: unless-stopped

  oneway-db:
    image: postgres:15
    environment:
      <<: *default-env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-oneway} -U ${POSTGRES_USER:-onewayuser}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - oneway-pg-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  oneway-app-data:
  oneway-pg-data:
  oneway-secrets:

networks:
  default:
    name: oneway-network