"""refactored ip_address from String to INET

Revision ID: 03ae50c160db
Revises: fbb039438577
Create Date: 2025-09-18 14:23:54.827359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03ae50c160db'
down_revision: Union[str, Sequence[str], None] = 'fbb039438577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "ip_address",
        existing_type=sa.VARCHAR(),
        type_=postgresql.INET(),
        existing_nullable=False,
        postgresql_using="ip_address::inet"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
