"""Change avatar to avatar_path

Revision ID: 1c47a456fbe1
Revises: 607f451126d4
Create Date: 2025-09-15 18:11:16.641266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c47a456fbe1'
down_revision: Union[str, Sequence[str], None] = '607f451126d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.String(), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###
