"""Add user_uuid foreign key to clients table

Revision ID: 53219e16ff8a
Revises: 54fdbc310ec1
Create Date: 2025-11-07 00:48:43.996155

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53219e16ff8a"
down_revision: Union[str, Sequence[str], None] = "54fdbc310ec1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add user_uuid column as nullable first to handle existing rows
    op.add_column("clients", sa.Column("user_uuid", sa.UUID(), nullable=True))

    # Get a connection to execute raw SQL
    conn = op.get_bind()

    # Get the first user's UUID to assign to existing clients
    result = conn.execute(sa.text("SELECT uuid FROM users LIMIT 1"))
    first_user = result.fetchone()

    if first_user:
        # Update existing clients to belong to the first user
        conn.execute(
            sa.text(
                "UPDATE clients SET user_uuid = :user_uuid WHERE user_uuid IS NULL"
            ),
            {"user_uuid": first_user[0]},
        )

    # Now make the column non-nullable
    op.alter_column("clients", "user_uuid", nullable=False)

    # Add the foreign key constraint
    op.create_foreign_key(None, "clients", "users", ["user_uuid"], ["uuid"])

    op.alter_column(
        "module_bucket_entry",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "module_bucket_entry",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_constraint(None, "clients", type_="foreignkey")
    op.drop_column("clients", "user_uuid")
    # ### end Alembic commands ###
