"""add client_modules table

Revision ID: 77fc142f162a
Revises: cbb00cfce59a
Create Date: 2025-09-10 19:28:07.169359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77fc142f162a'
down_revision: Union[str, Sequence[str], None] = 'cbb00cfce59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_modules',
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_name'], ['clients.username'], ),
    sa.ForeignKeyConstraint(['module_name'], ['modules.name'], ),
    sa.PrimaryKeyConstraint('client_name', 'module_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_modules')
    # ### end Alembic commands ###
