"""add client to module bucket

Revision ID: 7eee33c80d0a
Revises: e4041c52ab28
Create Date: 2025-10-28 12:46:50.777619

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7eee33c80d0a"
down_revision: Union[str, Sequence[str], None] = "e4041c52ab28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("module_bucket", sa.Column("client_uuid", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "module_bucket", "clients", ["client_uuid"], ["uuid"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "module_bucket", type_="foreignkey")
    op.drop_column("module_bucket", "client_uuid")
    # ### end Alembic commands ###
