"""refactor ModuleBucket with required data

Revision ID: 997f9bc5a9aa
Revises: dbcb513db2de
Create Date: 2025-10-14 20:36:35.965370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997f9bc5a9aa'
down_revision: Union[str, Sequence[str], None] = 'dbcb513db2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_bucket', 'data',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_bucket', 'data',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
