"""add ModuleBucket table

Revision ID: b858887b8225
Revises: 8cb2e3101f1c
Create Date: 2025-10-14 18:55:48.364632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b858887b8225'
down_revision: Union[str, Sequence[str], None] = '8cb2e3101f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_bucket',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('remove_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['module_name'], ['modules.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('module_name')
    )
    op.create_index(op.f('ix_module_bucket_uuid'), 'module_bucket', ['uuid'], unique=False)
    op.drop_constraint(op.f('client_modules_module_name_fkey'), 'client_modules', type_='foreignkey')
    op.drop_constraint(op.f('client_modules_client_name_fkey'), 'client_modules', type_='foreignkey')
    op.create_foreign_key(None, 'client_modules', 'modules', ['module_name'], ['name'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_modules', 'clients', ['client_name'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_modules', type_='foreignkey')
    op.drop_constraint(None, 'client_modules', type_='foreignkey')
    op.create_foreign_key(op.f('client_modules_client_name_fkey'), 'client_modules', 'clients', ['client_name'], ['username'])
    op.create_foreign_key(op.f('client_modules_module_name_fkey'), 'client_modules', 'modules', ['module_name'], ['name'])
    op.drop_index(op.f('ix_module_bucket_uuid'), table_name='module_bucket')
    op.drop_table('module_bucket')
    # ### end Alembic commands ###
