"""add relationship to client_modules

Revision ID: fa7ee08e64f2
Revises: 80cfd7bfc813
Create Date: 2025-09-10 17:07:26.159487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7ee08e64f2'
down_revision: Union[str, Sequence[str], None] = '80cfd7bfc813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
